version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=pQVq1CjKfASZuHxdOM5M
      - REDIS_URL=redis://redis:6379  
    depends_on:
      - mongodb
      - redis 
      - elasticsearch 

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"

  redis:  
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch: 
    image: elasticsearch:8.15.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node 
